name: gitlook
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: ">=2.17.6 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.2
    freezed_annotation: ^2.1.0
    dio: ^4.0.6
    json_annotation: ^4.6.0
    flutter_hooks: ^0.18.0
    hooks_riverpod: ^2.0.0-dev.9
    expandable: ^5.0.1
    font_awesome_flutter: ^10.1.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0
    build_runner: ^2.2.0
    freezed: ^2.1.0+1
    json_serializable: ^6.3.1
    mockito: ^5.3.0
    http_mock_adapter: ^0.3.3

flutter:
    uses-material-design: true
    assets:
        - assets/configuration.json
